---
title: "Stat 380 Final"
author: "Patrick Erickson, Aiden Shindel, Jordan Brophy"
format: 
  pdf:
    cite-method: biblatex
    pdf-engine: xelatex  
editor: visual
bibliography: references.bib
csl: mla.csl
nocite: |
  @*
appendix: true
execute:
  echo: false
  warning: false
  message: false
  cache: true
---

# Predicting Drowsy Driving: Can we Machine Learning Model to be able to Predict Drowsiness in Drivers?

## Introduction

### Intuition Behind the Choice of Data Set

In basketball, a number of statistics can be used in order to predict the winner of a game. For instance, a team's field goal percentage often correlates to the number of points that a team will score in any given game. Given these metrics, there has to be some combination of statistics that can ultimately help us predict if one team will win a game based on these statistics. In order to be able to perform this prediction, we must first find a data set that fits the parameters of the following:

-   The data set must be large to be able to get a good testing pool.
-   The data set has meaningful predictors are practically relevant to our test case.
-   The data set contains a winning/losing team variable
-   The data set follows **F.A.I.R.** and **C.A.R.E.** principles.

We ultimately landed on the *NCAA Regular Season Basketball Dataset* by Nate Duncan [^1], due to its extremely high case to variable ratio (90902:40), the fact that the data set had many predictors that would practically contribute to the winning or losing of a team, and that it had included a winning and losing team, which is our testing parameter.

[^1]: [@duncan2011]

### Ethical Considerations in the Choice of our Data Set

In order to ensure the ethical feasibility of the data set, we also scrutinized our selection to follow the **F.A.I.R.** and **C.A.R.E.** principles as discussed in class.

Since we had obtained our data from the open-source data hub Kaggle, we can ensure that anyone can **find** and **access** this data set through Kaggle's use guidelines, stating for a free distribution of data sets that are published for public use to practice ML or data analysis on. The data is also highly versatile, taking a csv format. This is one of the most **interoperable** formats there are for data sets, especially for our use-case in R, where reading in a csv is already built into the base. Lastly, the data set can be **reused** for multiple types of data analysis, and will always remain relevant for its time period.

In terms of **collective benefit**, the data set contributes to an overall understanding of basketball without harming any individuals or teams, due to the fact that it is simply raw data. Secondly, as I had stated the author's name, there is clearly ownership over the data set coming from sports-reference.com as Duncan mentioned, showing proper **Authority to Control**. Since proper attributions are maintained, it also falls under the **Responsibility and Ethics** guidelines of the C.A.R.E. principles.